# Numpy Array Basic

## 1. Numpy & ndarray

* Numpy (Numerical Python): library untuk komputasi numerik di python
* Struktur data inti bernama ndarray (n-dimensional array)
* array bisa 1D (vektor), 2D (matrik/table), atau lebih

## 2. List vs Numpy Array

Penjelasan

| Aspek                          | Python List                                   | NumPy Array                               |
| ------------------------------ | --------------------------------------------- | ----------------------------------------- |
| **Tipe data isi**              | Boleh campur (int, str, dll.)                 | Harus seragam (homogen)                   |
| **Kecepatan operasi numerik**  | Lambat (loop di level Python)                 | Cepat (dieksekusi di level C)             |
| **Operasi matematis langsung** | Tidak bisa (`[1, 2, 3] * 2` = duplikasi list) | Bisa (`arr * 2` = setiap elemen dikali 2) |
| **Penggunaan memori**          | Lebih boros                                   | Lebih hemat                               |


In [ ]:
# Python list
data = [1, 2, 3]
print(data * 2)
# Output: [1, 2, 3, 1, 2, 3]  <- list-nya digandakan, BUKAN dikali per elemen

#  Numpy Array  
import numpy as np
arr = np.array([1, 2, 3])
print(arr * 2)
# Output: [2 4 6]  <- setiap elemen dikali 2

[1, 2, 3, 1, 2, 3]
[2 4 6]


## Membuat array: np.array(), np.zeros(), np.ones()

In [5]:
import numpy as np

# Dari list python biasa
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Array 2D matriks - dari list of list
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Array berisi 0 
zeros = np.zeros((2, 3))  # 2 baris, 3 kolom, semua isi 0.0
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Array berisi satu
ones = np.ones((4, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



## 4. np.arange() dan np.linespace()

Membuat deret angka tetapi logika berbeda

* arange(start, stop, step): menentukan jarak lompatannya, jumlah elemen tidak pasti
* linspace(start, stop, num): tentukan jumlah elemennya, jarak dihitung otomatis, dan stop disertakan (inklusif), beda dengan arange yang eksklusif di batas atas

In [ ]:
# np.arange: berdasarkan step (Jarak antar angka)
arange = np.arange(1, 10, 2)   # mulai 0, sampai <10, loncat 2
print(arange)

[1 3 5 7 9]


In [11]:
# linespace: berdasarkan jumlah titik yang diinginkan
linspace = np.linspace(0, 10, 5) # 5 titik, jaraknya rata dari 0 sampai 10
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


## 5. Properti Array: shape, ndim, size

* shape: bentuk array (baris, kolom)
* ndim:  berapa banyak dimensi
* size : Total elemen di seluruh array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)   # (2, 3)  -> 2 baris, 3 kolom
print(arr.ndim)    # 2       -> jumlah dimensi (2D)
print(arr.size)    # 6       -> total elemen (2 x 3)

(2, 3)
2
6


## 6. dtype

In [14]:
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)      # int64

arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype)    # float64

arr_bool = np.array([True, False, True])
print(arr_bool.dtype)     # bool

# Mengubah tipe data
arr_konversi = arr_int.astype(np.float32)
print(arr_konversi.dtype)  # float32

int64
float64
bool
float32


## 7. Operasi Aritmetika Dasar

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)   # [11 22 33]  -> elemen sejajar dijumlahkan
print(a - b)   # [-9 -18 -27]
print(a * b)   # [10 40 90]  -> perkalian elemen sejajar (bukan perkalian matriks!)
print(b / a)   # [10. 10. 10.]

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[10. 10. 10.]
