# 1. NumPy Array Basics

## Fokus Bab

Bab ini membangun fondasi pemahaman terhadap ndarray, struktur data inti yang menjadi dasar hampir seluruh ekosistem komputasi numerik Python (Pandas, scikit-learn, TensorFlow, PyTorch). Tanpa pemahaman yang solid terhadap ndarray, konsep-konsep lanjutan seperti broadcasting dan vectorization akan sulit dipahami secara intuitif.

## Tujuan Pembelajaran

* Menjelaskan apa itu ndarray dan mengapa struktur data ini menjadi fondasi ekosistem numerik Python (Pandas, scikit-learn, dll).
* Membedakan karakteristik ndarray dengan Python list, khususnya dari sisi homogenitas tipe data dan performa.
* Membuat array menggunakan berbagai fungsi konstruktor sesuai kebutuhan (nilai eksplisit, nilai default, rangkaian angka).
* Membaca dan menginterpretasikan atribut struktural array (shape, ndim, size, dtype) untuk keperluan debugging.
* Memahami hubungan antara pemilihan dtype dengan efisiensi penggunaan memori.
* Melakukan operasi aritmatika dasar secara element-wise pada array.

## Isi Materi

* NumPy dan ndarray — definisi NumPy, konsep ndarray, peran NumPy dalam Data Science, serta perbandingan NumPy dengan Python list.
* Membuat Array — fungsi konstruktor: np.array(), np.zeros(), np.ones(), np.full(), np.arange(), np.linspace().
* Struktur Array — atribut shape, ndim, size, dan dtype sebagai alat utama membaca karakteristik array.
* Data Type — tipe data integer, float, boolean; konversi tipe dengan .astype(); dan dampak dtype terhadap konsumsi memori.
* Operasi Dasar — operator aritmatika element-wise (+, -, *, /, **) beserta perbedaannya dengan operator yang sama pada Python list.

## Goals

Mampu membuat array dan memahami struktur serta tipe datanya — sebagai fondasi sebelum masuk ke manipulasi data (indexing, slicing, masking) pada bab-bab selanjutnya.

## 1.1 NumPy dan `ndarray`

NumPy (Numerical Python) adalah pustaka fundamental untuk komputasi ilmiah di Python. NumPy menyediakan objek array multidimensi berperforma tinggi bernama ndarray (n-dimensional array), beserta kumpulan fungsi untuk beroperasi secara efisien pada array tersebut.

* `ndarray` adalah struktur data berbentuk grid dari nilai-nilai yang bertipe sama (homogen), diindeks oleh tuple bilangan bulat non-negatif. Berbeda dengan list Python yang dapat menampung tipe data campuran, ndarray mengharuskan seluruh elemen memiliki tipe data yang seragam.
* Peran NumPy dalam Data Science sangat sentral karena hampir seluruh library numerik di Python — Pandas, scikit-learn, SciPy, Matplotlib — dibangun di atas atau berinteroperasi langsung dengan ndarray. Memahami NumPy berarti memahami "bahasa" yang dipakai oleh seluruh stack tersebut.
* NumPy vs Python List — perbedaan mendasarnya terletak pada implementasi dan performa:

| Aspek                  | Python List                     | NumPy `ndarray`                                  |
| ---------------------- | ------------------------------- | ------------------------------------------------ |
| **Tipe data**          | Heterogen (boleh campur)        | Homogen (satu tipe data)                         |
| **Penyimpanan memori** | Tersebar (*array of pointers*)  | *Contiguous block* (blok memori berurutan)       |
| **Operasi elemen**     | Perlu loop eksplisit            | *Vectorized* (operasi langsung ke seluruh array) |
| **Kecepatan**          | Relatif lambat untuk data besar | Jauh lebih cepat untuk operasi numerik           |


Kecepatan NumPy berasal dari fakta bahwa operasi-operasinya diimplementasikan dalam C dan dieksekusi tanpa overhead interpreter Python pada setiap elemen — inilah alasan mengapa operasi numerik skala besar (jutaan baris data) menjadi praktis dilakukan.

## 1.2 Membuat Array

In [1]:
import numpy as np

Dari struktur data python (list/tuple)

In [4]:
arr = np.array([1, 2, 3, 4])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4]


 Array berisi nol — sering dipakai sebagai inisialisasi (misal, akumulator)

In [6]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


Array berisi satu — sering dipakai untuk menambahkan kolom bias/intercept

In [7]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


Array berisi nilai konstan tertentu


In [8]:
full = np.full((2, 3), 7)
print(full)

[[7 7 7]
 [7 7 7]]


Rangkaian nilai dengan step tertentu (mirip range() bawaan Python)

In [9]:
arange = np.arange(0, 10, 2)
print(arange)

[0 2 4 6 8]


Rangkaian nilai dengan jumlah titik tertentu, merata (linear spacing)

In [10]:
linspace = np.linspace(0, 1, 5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


Perbedaan konseptual penting antara np.arange() dan np.linspace():

* np.arange(start, stop, step) — Anda menentukan step (jarak antar elemen), jumlah elemen hasil dihitung otomatis.
* np.linspace(start, stop, num) — Anda menentukan jumlah elemen (num) yang diinginkan, step dihitung otomatis agar merata dari start sampai stop (inklusif secara default).

np.zeros() dan np.ones() sangat umum dipakai sebagai titik awal (placeholder) sebelum array diisi nilai hasil komputasi, sementara np.full() berguna ketika nilai awal bukan 0 atau 1.

## 1.3 Struktur Array

Setiap ndarray memiliki empat atribut struktural yang esensial untuk dipahami:

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

2

### shape 

- tuple menunjukan ukuran array pada setiap dimensi

In [12]:
print(arr.shape)

(2, 3)


### ndim

- Jumlah dimensi / axis array. Array 1D memiliki `ndim=1` (vektor), array 2D memiliki `ndim=2` (matriks)

In [13]:
print(arr.ndim)

2


### size 

- jumlah total elemen dalam array, setara dengan hasil perkalian seluruh komponen shape.

In [14]:
print(arr.size)

6


### dtype 

- tipe data dari elemen-elemen array. Karena ndarray bersifat homogen, seluruh elemen berbagi satu dtype yang sama.

In [15]:
print(arr.dtype)

int64


Ilustrasi hubungan antar atribut ini untuk array 2D berukuran (2, 3)

![Ilustrasi hubungan antar atribut ini untuk array 2D berukuran (2, 3)](../assets/figures/numpy_array_structure.png)

Diagram di atas menggambarkan hubungan langsung antara isi array dan atributnya: shape merepresentasikan dimensi baris×kolom, ndim menunjukkan berapa lapis dimensi tersebut, dan size adalah hasil perkalian seluruh komponen shape.

## 1.4 Data Type (dtype)

ndarray bersifat homogen, sehingga NumPy perlu mengalokasikan memori secara efisien berdasarkan satu tipe data yang berlaku untuk seluruh elemen.

> Homogen: semua elemen dalam ndarray menggunakn satu tipe data yang sama 

Tipe data utama yang umum dijumpai:

* Integer — `int8, int16, int32, int64` (angka menunjukkan jumlah bit yang dialokasikan per elemen)
* Float — `float16, float32, float64` (default pada kebanyakan sistem)
* Boolean — bool, menyimpan True/False, banyak dipakai untuk boolean masking

Konversi tipe data menggunakan `astype()`

In [17]:
arr = np.array([1, 2,3])
arr_float = arr.astype(np.float16)
print(arr.dtype)
print(arr_float.dtype)

int64
float16


* **`dtype`** menentukan tipe data dan ukuran memori setiap elemen.
* Semakin besar **bit** yang dialokasikan, semakin besar pula **memori** yang digunakan.
* Contoh untuk **1 juta elemen**:

  * `int64` → sekitar **8 MB**
  * `int8` → sekitar **1 MB**, jika rentang nilainya memungkinkan.
* Dalam Data Science dengan dataset besar, pemilihan **`dtype` yang tepat** dapat menjadi teknik optimasi memori yang signifikan.
* Optimasi `dtype` sering diabaikan pemula, tetapi **berdampak besar pada dataset berskala besar**.


## 1.5 Operasi Dasar

NumPy mendukung operasi aritmatika element-wise secara langsung tanpa perlu loop:

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5, 7, 9]   → penjumlahan per elemen
print(a - b)   # [-3, -3, -3] → pengurangan per elemen
print(a * b)   # [4, 10, 18]  → perkalian per elemen
print(a / b)   # [0.25, 0.4, 0.5] → pembagian per elemen
print(a ** 2)  # [1, 4, 9]    → pemangkatan per elemen

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


* Operator pada NumPy bekerja secara **element-wise**, yaitu operasi diterapkan pada elemen di **posisi yang sama** antar-array.
* Operasi ini **bukan perkalian matriks** seperti dalam aljabar linear konvensional.
* Berbeda dengan Python `list`:

  * `list` → operator `+` melakukan **concatenation**.
  * `ndarray` → operator `+` melakukan **penjumlahan element-wise**.
* Contoh:

  ```python
  [1, 2] + [3, 4]        # [1, 2, 3, 4]
  np.array([1, 2]) + np.array([3, 4])  # [4, 6]
  ```


# Ringkasan

| Konsep              | Fungsi/Atribut Kunci                                               | Kegunaan Utama                      |
| ------------------- | ------------------------------------------------------------------ | ----------------------------------- |
| **Struktur data**   | `ndarray`                                                          | Fondasi seluruh operasi numerik     |
| **Pembuatan array** | `array()`, `zeros()`, `ones()`, `full()`, `arange()`, `linspace()` | Inisialisasi data                   |
| **Struktur**        | `shape`, `ndim`, `size`, `dtype`                                   | Debugging & pemahaman dimensi       |
| **Tipe data**       | `astype()`                                                         | Optimasi memori & tipe data         |
| **Operasi dasar**   | `+`, `-`, `*`, `/`, `**`                                           | Transformasi numerik *element-wise* |
