# NumPy Indexing & Slicing

##  Fokus Bab

Bab ini membahas cara mengambil (akses) dan memodifikasi bagian tertentu dari array — baik pada array 1D maupun 2D. Kemampuan ini menjadi dasar untuk hampir seluruh manipulasi data numerik, termasuk persiapan fitur (feature engineering) di tahap selanjutnya.

## Tujuan Pembelajaran

* Mengakses elemen tunggal pada array 1D menggunakan positive maupun negative indexing.
* Mengakses elemen, baris, atau kolom pada array 2D menggunakan format arr[row, column].
* Mengambil subset (rentang) data menggunakan slicing dengan format start:end:step, baik pada array 1D maupun 2D.
* Memodifikasi satu atau beberapa elemen array secara langsung melalui indexing maupun slicing.
* Menjelaskan konsep view pada hasil slicing dan mengidentifikasi potensi silent bug akibat perilaku berbagi memori antara slice dan array asli.

## Isi Materi

* Indexing 1D — positive indexing (dari kiri, mulai 0) dan negative indexing (dari kanan, mulai -1).
* Indexing 2D — format arr[row, column], cara mengakses baris utuh (arr[i, :]) dan kolom utuh (arr[:, j]).
* Slicing — aturan start:end:step dengan end bersifat eksklusif; penerapannya pada baris dan kolom array 2D.
* Modifikasi — mengubah satu elemen langsung (arr[i] = val) maupun beberapa elemen sekaligus melalui slicing (arr[i:j] = val).
* View Introduction — perbedaan mendasar slicing NumPy dengan slicing Python list; hasil slice berbagi memori dengan array asli, sehingga modifikasi pada slice ikut mengubah array sumbernya.


## Goals (Target Output)

Mampu mengambil dan memodifikasi bagian tertentu dari array secara tepat, sekaligus memahami implikasi view agar terhindar dari perubahan data yang tidak disengaja — kemampuan dasar sebelum masuk ke boolean masking pada bab 3.

## Indexing 1D

* Indexing proses mengambil / mengakses elemen tunggal dengan array menggunakan posisi (Index).
* Arah pengindexan array
    - Positive indexing — dimulai dari 0 di elemen paling kiri, bertambah ke kanan.
    - Negative indexing — dimulai dari -1 di elemen paling kanan, bertambah ke kiri.

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])
print(arr[-0])

print(arr[0])    # 10  → elemen pertama (positive indexing)
print(arr[2])    # 30  → elemen ketiga
print(arr[-1])   # 50  → elemen terakhir (negative indexing)
print(arr[-2])   # 40  → elemen kedua dari belakang)

10
50
10
10
30
50
40


Beberapa hal yang perlu diperhatikan:

* Negative indexing sangat berguna ketika Anda ingin mengakses elemen dari akhir array tanpa perlu mengetahui panjang array (len(arr)) terlebih dahulu.
* Index yang melebihi batas array (arr[10] pada array berisi 5 elemen) akan memicu IndexError.

## Indexing 2D

Pada array 2D indexing dilakukan dengan arr[row, column].

* Format ini berbeda dari Python list bersarang (nested list) yang biasanya diakses dengan arr[row][column].
* NumPy menyederhanakan akses menjadi satu pasang kurung siku dengan koma sebagai pemisah axis.

In [7]:
arr2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr2d[0, 0])
print(arr2d[0, 0])   # 1  → baris ke-0, kolom ke-0
print(arr2d[1, 2])   # 6  → baris ke-1, kolom ke-2
print(arr2d[-1, -1]) # 9  → baris terakhir, kolom terakhir

1
1
6
9


Mengakses kolom secara penuh gunakan : (colon) sebagai penanda "Seluruh elemen pada axis tersebut

In [9]:
print(arr2d[:5])
arr2d[0, :]   # [1, 2, 3]  → seluruh kolom pada baris ke-0
arr2d[:, 0]   # [1, 4, 7]  → seluruh baris pada kolom ke-0

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 4, 7])

## Slicing

Slicing memungkinkan pengambilan rentang (subset) elemen sekaligus, menggunakan format  `start:end:step`. Beberapa aturan pentingnya:

* start — index awal (inklusif, defaultnya 0)
* end — index akhir (eksklusif, tidak ikut terambil)
* step — jarak antar elemen yang diambil (defaultnya 1)

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:5])     # [2, 3, 4]      → index 2 sampai 4 (5 tidak ikut)
print(arr[:4])      # [0, 1, 2, 3]   → dari awal sampai index 3
print(arr[6:])      # [6, 7, 8, 9]   → dari index 6 sampai akhir
print(arr[::2])     # [0, 2, 4, 6, 8] → setiap 2 elemen (step=2)
print(arr[::-1])    # [9, 8, 7, ..., 0] → reverse array

[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


Ilustrasi visual pemahaman slicing pada array 2D:

![Ilustrasi visual untuk mempermudah pemahaman slicing pada array 2D:](../assets/figures/numpy_2d_slicing.png)

## Modifikasi

### Mengubah satu elemen

In [11]:
arr = np.array([10, 20, 30, 40, 50])

arr[3] = 9999
print(arr)

[  10   20   30 9999   50]


### Mengubah beberapa elemen

In [12]:
arr = np.array([10, 20, 30, 40, 50])
arr[1:4] = 0
print(arr)

# arr → [10, 0, 0, 0, 50]


[10  0  0  0 50]


Beberapa catatan penting seputar modifikasi array:

* Modifikasi juga berlaku pada array 2D, misalnya arr2d[0, :] = [100, 200, 300] akan mengganti seluruh isi baris ke-0.
* Ketika nilai skalar tunggal (seperti 0 pada contoh di atas) diberikan ke slice yang berisi banyak elemen, NumPy secara otomatis "menyebarkan" nilai tersebut ke seluruh posisi — perilaku ini adalah bentuk sederhana dari broadcasting, konsep yang akan dibahas lebih dalam pada bab 4.

## View Introduction

Konsep ini merupakan salah satu titik krusial yang sering menjebak pemula. Perhatikan poin-poin berikut sebelum melanjutkan ke praktik:

* Ketika Anda melakukan slicing pada array NumPy, hasilnya bukanlah array baru yang independen, melainkan sebuah view — semacam "jendela" yang menunjuk ke data yang sama di memori dengan array aslinya.
* Konsekuensinya, jika Anda memodifikasi elemen pada hasil slice, perubahan tersebut akan ikut mengubah array aslinya.

In [13]:
arr = np.array([10, 20, 30, 40, 50])

slice_arr = arr[1:4]
slice_arr[0] = 99

print(arr)
print(slice_arr)


[10 99 30 40 50]
[99 30 40]


Poin penting terkait perilaku ini:

* Perilaku ini berbeda dari slicing pada Python list biasa, yang selalu menghasilkan copy independen.
* Perilaku "berbagi memori" ini sengaja dirancang NumPy demi efisiensi memori dan performa, terutama saat bekerja dengan array besar — membuat copy setiap kali slicing akan sangat boros memori dan waktu.
* Jika Anda memang menginginkan array independen (bukan view), gunakan method .copy(), yang akan dibahas secara menyeluruh pada bab 9 (Copy vs View).
* Untuk saat ini, cukup pahami: slicing menghasilkan view, dan Anda perlu berhati-hati saat memodifikasi hasil slice jika tidak ingin array aslinya ikut berubah secara tidak sengaja.

## Ringkasan

| Konsep          | Sintaks Kunci         | Kegunaan Utama                                               |
| --------------- | --------------------- | ------------------------------------------------------------ |
| **Indexing 1D** | `arr[i]`, `arr[-i]`   | Akses elemen tunggal                                         |
| **Indexing 2D** | `arr[row, col]`       | Akses elemen pada matriks                                    |
| **Slicing**     | `arr[start:end:step]` | Mengambil rentang data                                       |
| **Modifikasi**  | `arr[idx] = val`      | Mengubah nilai array                                         |
| **View**        | Hasil slice = *view*  | Efisiensi memori, tetapi berpotensi menimbulkan *silent bug* |
