# NumPy Indexing & Slicing

## Indexing 1D

posisi dimulai dari 0

In [2]:
import numpy as np

arr = np.array([10, 12, 16, 13, 17, 16, 14])

print(arr[0]) # Elemen pertama
print(arr[5]) # Elemen keenam

10
16


## Indexing 2D

array 2D butuh 2 kordinat: [baris, kolom]

In [7]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"Ambil 5: {arr2d[1, 1]}")
print(f"Ambil 7: {arr2d[2, 0]}")

Ambil 5: 5
Ambil 7: 7


Note:

*  arr2d[1, 2] bukan arr2d[1][2] walau hasilnya sama
* Bentuk arr[baris, kolom] adalah numpy lebih efisien dibanding bentuk arr[1][2] (yang sebenarnya mengakses dua kali, seperti list of list Python biasa).

## Indexing 3D Secara Dasar

Array 3D butuh tiga koordinat: [depth, baris, kolom]

In [11]:
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])


print(arr3d.shape) # (2, 2, 2) -> 2 tumpukan, masing-masing 2x2

print(arr3d[0]) # Tumpukan pertama: [[1, 2], [3, 4]]
print()
print(arr3d[0, 1]) # baris ke 1, tumpukan pertama
print()
print(arr3d[0, 1, 0]) # elemen tunggal 3

(2, 2, 2)
[[1 2]
 [3 4]]

[3 4]

3


## Negative Indexing

Index negative = hitung dari belakang. -1 = elemen terkhir, -2 = elemen kedua dari belakang

In [12]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])    # 50  -> elemen terakhir
print(arr[-2])    # 40  -> elemen kedua dari belakang

50
40


In [13]:
arr2d = np.array([[1,2,3],[4,5,6]])

print(arr2d[-1, -1])

6


## Slicing 1D

format: arr[start:end] - mengambil dari index start sampai end-1 (batas atas eksklusif, sama seprti range())

In [19]:
arr = np.array([10, 20, 30, 40, 50 ,60])

print(arr[1:4])     # [20 30 40]  -> index 1,2,3 (bukan sampai 4!)
print(arr[:3])      # [10 20 30]  -> dari awal sampai index 2
print(arr[3:])      # [40 50 60]  -> dari index 3 sampai akhir
print(arr[::2])     # [10 30 50] > loncat 2 step
print(arr[::-1])     # [60 50 40 30 20 10]  -> membalik array!

[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[60 50 40 30 20 10]


## Slicing baris dan kolom 2D

In [20]:
arr2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12]
])

In [21]:
print(arr2d[0:2, :]) # ambil baris 0 sampai satu semua kolom

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
print(arr2d[1:2, 0:2]) # Ambil baris ke 1, kolom 0 s 1

[[5 6]]


In [27]:
print(arr2d[:, 1:3])     # semua baris, kolom 1-2
# [[2 3]
#  [6 7]
#  [10 11]]

print(arr2d[1, :])       # baris index 1 saja (1D hasilnya)
# [5 6 7 8]

print(arr2d[:, 0])       # kolom index 0 saja (1D hasilnya)

[[ 2  3]
 [ 6  7]
 [10 11]]
[5 6 7 8]
[1 5 9]


Pola arr[start:end, start:end] ini adalah format universal untuk slicing 2D: bagian sebelum koma = baris, bagian setelah koma = kolom.

## Mengubah nilai melalui indexing

In [28]:
arr = np.array([10, 20, 30, 40, 50])
arr[0] = 99
print(arr)

[99 20 30 40 50]


In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d[0, 1] =100

print(arr2d)

[[  1 100   3]
 [  4   5   6]]


In [30]:
# Mengubah seluruh slice sekaligus
arr[1:3] = 0
print(arr)

[99  0  0 40 50]


## Slicing Menghasilkan VIEW, Bukan Copy!

* Slicing, numpy tidak membuat array baru > hanya menampilkan

In [32]:
original = np.array([1, 2, 3, 4, 5])

slice_view = original[1:4]     # ini VIEW, bukan array baru!
print(slice_view)              # [2 3 4]

slice_view[0] = 999             # ubah view...
print(slice_view)               # [999 3 4]
print(original)                 # [1 999 3 4 5]  <- ASLI IKUT BERUBAH! 😱

[2 3 4]
[999   3   4]
[  1 999   3   4   5]


In [33]:
original = np.array([1, 2, 3, 4, 5])

slice_copy = original[1:4].copy()   # ini COPY, array baru terpisah
slice_copy[0] = 999

print(slice_copy)   # [999 3 4]
print(original)     # [1 2 3 4 5]  <- ASLI TETAP AMAN

[999   3   4]
[1 2 3 4 5]


Cara memeriksa apakah suatu array adalah view:

In [34]:
print(slice_view.base is original)   # True -> berarti view (berbagi memori)
print(slice_copy.base is original)   # False -> berarti copy independen

False
False
