# Aggregation & Axis

## Fokus Bab

Bab ini membahas dua kemampuan yang saling berkaitan erat: aggregation (operasi statistik dasar seperti sum, mean, std) dan axis (parameter yang menentukan arah agregasi dilakukan pada array multidimensi). Salah paham terhadap axis adalah salah satu kesalahan paling umum di kalangan pemula NumPy, sehingga bab ini akan membahasnya secara mendalam agar tidak lagi bergantung pada trial-and-error.

## Tujuan Pembelajaran

Setelah menyelesaikan bab ini, Anda diharapkan mampu:

* Menggunakan fungsi agregasi dasar (`sum`, `mean`, `median`, `std`, `var`, `min`, `max`) pada array NumPy.
* Menggunakan `argmin` dan `argmax` untuk menemukan posisi nilai ekstrem, bukan hanya nilainya.
* Menjelaskan dan menerapkan parameter `axis` pada array 2D secara tepat, tanpa perlu menebak-nebak.
* Menjelaskan fungsi parameter `keepdims` dan hubungannya dengan `broadcasting`.
* Menerapkan `aggregation` dan `axis` untuk studi kasus nyata: menghitung statistik per fitur pada dataset.

## Isi Materi

Aggregation Functions — fungsi statistik dasar (`sum`, `mean`, `median`, `std`, `var`, `min`, `max`) dan position aggregation (`argmin`, `argmax`).
Axis — konsep axis pada array multidimensi, perbedaan `axis=0` dengan `axis=1`, serta parameter `keepdims`.
Studi Kasus Data Science — penerapan aggregation dan axis untuk menghitung mean, std, dan min/max per fitur pada dataset tabular.

## Goals

Mampu menggunakan aggregation dan axis tanpa trial-and-error.

# 1. Aggregation Functions

## 1.1 Fungsi Agregasi Dasar

Aggregation adalah proses meringkas banyak nilai menjadi satu nilai representatif (misalnya total, rata-rata, atau variasi). NumPy menyediakan fungsi-fungsi ini sebagai method langsung pada ndarray

In [9]:
import numpy as np

In [10]:
nilai = np.array([70, 85, 90, 60, 75])

print(nilai.sum())      # 380   → total keseluruhan
print(nilai.mean())     # 76.0  → rata-rata
print(np.median(nilai)) # 75.0  → nilai tengah setelah diurutkan
print(nilai.std())      # 10.42 → standar deviasi (sebaran data)
print(nilai.var())      # 108.6 → variance (std kuadrat)
print(nilai.min())      # 60    → nilai terkecil
print(nilai.max())      # 90    → nilai terbesar


380
76.0
75.0
10.677078252031311
114.0
60
90


Penjelasan kode di atas:

* `sum()`, `mean()`, `min()`, `max()`, `std()`, dan `var()` dapat digunakan sebagai method pada array, misalnya `nilai.mean()`.
* `median()` umumnya digunakan melalui fungsi NumPy, yaitu `np.median(nilai)`.
* `std()` mengukur penyebaran data dalam satuan yang sama dengan data asli.
* `var()` merupakan kuadrat dari `std()`, sehingga satuannya juga menjadi kuadrat dari satuan data.
* Fungsi-fungsi tersebut melakukan operasi terhadap array tanpa perlu menulis loop Python secara manual.


## 1.2 Position Aggregation — `argmin` & `argmax`

Berbeda dari `min()`/`max()` yang mengembalikan nilai, `argmin()`/`argmax()` mengembalikan posisi (indeks) dari nilai tersebut:

In [11]:
nilai = np.array([70, 85, 90, 60, 75])

print(f"Nilai Max {nilai.max()}")
print(f"Posisi Index nilai max: {nilai.argmax()}")

print(f"\nNilai min: {nilai.min()}")
print(f"Posisi Index nilai min: {nilai.argmin()}")

Nilai Max 90
Posisi Index nilai max: 2

Nilai min: 60
Posisi Index nilai min: 3


Penjelasan kode di atas:

* `argmax()` mengembalikan indeks posisi dari nilai terbesar, bukan nilai terbesarnya.
* `argmin()` mengembalikan indeks posisi dari nilai terkecil.
* Contoh penggunaan:

  ```python
  nama_siswa[nilai.argmax()]
  ```

  digunakan untuk mendapatkan nama siswa dengan nilai tertinggi.
* Pada output model klasifikasi, `argmax()` dapat digunakan untuk menentukan kelas dengan probabilitas tertinggi.
* Jika terdapat beberapa nilai maksimum/minimum yang sama, `argmax()`/`argmin()` mengembalikan indeks pertama yang ditemukan.


# 2. Axis


## 2.1 Konsep Axis pada Array Multidimensi

### Axis pada NumPy

`axis` adalah istilah NumPy untuk menunjukkan dimensi atau arah pada sebuah array. Parameter ini digunakan oleh banyak operasi agregasi seperti `sum()`, `mean()`, `min()`, dan `max()` untuk menentukan dimensi mana yang akan diringkas.

#### 1. Axis pada Array 1D

Array 1D hanya memiliki satu axis, yaitu `axis=0`.

```python
arr = np.array([10, 20, 30, 40])
````

```text
shape = (4,)
         ↑
      axis=0
```

Operasi:

```python
arr.sum(axis=0)
```

menghasilkan:

```text
10 + 20 + 30 + 40 = 100
```

Hasil:

```python
100
```

#### 2. Axis pada Array 2D

Array 2D memiliki dua axis:

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

Shape:

```text
shape = (2, 3)
         │  │
         │  └── axis=1
         └───── axis=0
```

Secara visual:

```text
        axis=1 →
        
        1   2   3
        4   5   6
        ↓
      axis=0
```

Untuk menghindari kebingungan, `axis=0` dapat dipahami sebagai arah vertikal dan `axis=1` sebagai arah horizontal.

#### 3. Agregasi Tanpa `axis`

Jika `axis` tidak diberikan:

```python
arr.sum()
```

NumPy menjumlahkan seluruh elemen array:

```text
1 + 2 + 3 + 4 + 5 + 6 = 21
```

Hasil:

```python
21
```

Shape hasil:

```text
(2, 3) → ()
```

Seluruh array diringkas menjadi satu nilai.

#### 4. Agregasi dengan `axis=0`

```python
arr.sum(axis=0)
```

Agregasi dilakukan sepanjang `axis=0`:

```text
       1   2   3
       4   5   6
       ↓   ↓   ↓
       +   +   +
       5   7   9
```

Perhitungan:

```text
1 + 4 = 5
2 + 5 = 7
3 + 6 = 9
```

Hasil:

```python
[5, 7, 9]
```

Shape:

```text
(2, 3) → (3,)
```

`axis=0` hilang karena dimensi tersebut telah diagregasi.

#### 5. Agregasi dengan `axis=1`

```python
arr.sum(axis=1)
```

Agregasi dilakukan sepanjang `axis=1`:

```text
1 + 2 + 3 = 6
4 + 5 + 6 = 15
```

Hasil:

```python
[6, 15]
```

Shape:

```text
(2, 3) → (2,)
```

`axis=1` hilang karena dimensi tersebut telah diagregasi.

### Ringkasan

| Operasi           | Axis yang diagregasi | Hasil       | Shape  |
| ----------------- | -------------------- | ----------- | ------ |
| `arr.sum()`       | Semua dimensi        | `21`        | `()`   |
| `arr.sum(axis=0)` | `axis=0`             | `[5, 7, 9]` | `(3,)` |
| `arr.sum(axis=1)` | `axis=1`             | `[6, 15]`   | `(2,)` |

### Inti

> `axis` menentukan dimensi yang digunakan sebagai arah agregasi. Dimensi yang diagregasi akan hilang dari `shape` hasil, sedangkan dimensi lainnya tetap dipertahankan.

```
```


## 2.2 axis=0 vs axis=1

* Kesalahan umum: mengira `axis=0` berarti operasi dilakukan per baris.
* Makna yang lebih tepat: `axis=0` berarti operasi dilakukan sepanjang arah baris, sehingga hasilnya tersisa per kolom.
* `axis=1` berarti operasi dilakukan sepanjang arah kolom, sehingga hasilnya tersisa per baris.


In [2]:
import numpy as np

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(matrix.sum(axis=0))   # [12, 15, 18]
print(matrix.sum(axis=1))   # [6, 15, 24]

[12 15 18]
[ 6 15 24]


![numpy_axis_0_vs_axis_1.png](../assets/figures/axis_0_vs_axis_1.png)

### 📖 Deep Dive — Cara Membaca axis yang Benar

* `axis` menunjukan dimensi array yang menjadi arah reduksi (reduction)
* `axis=0`: agregasi dilakukan sepanjang dimensi baris, sehingga dimensi `axis=0` dihilangkan dan menghasilkan satu nilai untuk setiap kolom.
* `axis=1`: agregasi dilakukan sepanjang dimensi kolom, sehingga dimensi `axis=1` dihilangkan dan menghasilkan satu nilai untuk setiap kolom.
* Prinsip utama: axis adalah dimensi yang di-collapse oleh operasi agregasi.
* Prinsip ini berlaku konsisten pada `sum()`, `mean()`, `std()`, `min()`, `max()`, dan fungsi agregasi lainnya.

## 2.3 keepdims dan Hubungannya dengan Broadcasting

* `keepdims` menentukan apakah dimensi yang digunakan dalam operasi agregasi dipertahankan dalam hasil
* Default: `keepdims=False` sehingga dimensi yang diagregasi dihilangkan.
* Dengan `keepdims=True`, dimensi tersebut tetap dipertahankan dengan ukuran 1.

### 1. Perilaku Default

In [4]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

(2, 3)


In [5]:
hasil = arr.mean(axis=0)
print(hasil)
print(f"Shape default: {hasil.shape}")

[2.5 3.5 4.5]
Shape default: (3,)


`axis=0` diagregasi, sehingga dimensi tersebut hilang

```text
______________________
Sebelum       : (2, 3)
                  ↓
mean(axis=0)  : (3,)
_______________________
```
Hasilnya memiliki satu nilai di setiap kolom

### 2. Dengan `keepdims=True`

In [6]:
hasil = arr.mean(axis=0, keepdims=True)

print(hasil)
print(f"Shape default: {hasil.shape}")


[[2.5 3.5 4.5]]
Shape default: (1, 3)


Dimensi `axis=0` tidak dihilangkan, tetapi ukurannya menjadi 1:


```text
______________________
Sebelum       : (2, 3)
                  ↓
mean(axis=0)  : (1, 3)
______________________
```

Perbandingan

| Operasi                       | Shape hasil | Dimensi agregasi          |
| ----------------------------- | ----------: | ------------------------- |
| `mean(axis=0)`                |      `(3,)` | Hilang                    |
| `mean(axis=0, keepdims=True)` |    `(1, 3)` | Dipertahankan sebagai `1` |




### 3.  keepdims untuk broadcasting

`keepdims