# Aggregation & Axis

## Fokus Bab

Bab ini membahas dua kemampuan yang saling berkaitan erat: aggregation (operasi statistik dasar seperti sum, mean, std) dan axis (parameter yang menentukan arah agregasi dilakukan pada array multidimensi). Salah paham terhadap axis adalah salah satu kesalahan paling umum di kalangan pemula NumPy, sehingga bab ini akan membahasnya secara mendalam agar tidak lagi bergantung pada trial-and-error.

## Tujuan Pembelajaran

Setelah menyelesaikan bab ini, Anda diharapkan mampu:

* Menggunakan fungsi agregasi dasar (`sum`, `mean`, `median`, `std`, `var`, `min`, `max`) pada array NumPy.
* Menggunakan `argmin` dan `argmax` untuk menemukan posisi nilai ekstrem, bukan hanya nilainya.
* Menjelaskan dan menerapkan parameter `axis` pada array 2D secara tepat, tanpa perlu menebak-nebak.
* Menjelaskan fungsi parameter `keepdims` dan hubungannya dengan `broadcasting`.
* Menerapkan `aggregation` dan `axis` untuk studi kasus nyata: menghitung statistik per fitur pada dataset.

## Isi Materi

Aggregation Functions — fungsi statistik dasar (`sum`, `mean`, `median`, `std`, `var`, `min`, `max`) dan position aggregation (`argmin`, `argmax`).
Axis — konsep axis pada array multidimensi, perbedaan `axis=0` dengan `axis=1`, serta parameter `keepdims`.
Studi Kasus Data Science — penerapan aggregation dan axis untuk menghitung mean, std, dan min/max per fitur pada dataset tabular.

## Goals

Mampu menggunakan aggregation dan axis tanpa trial-and-error.

# 1. Aggregation Functions

## 1.1 Fungsi Agregasi Dasar

Aggregation adalah proses meringkas banyak nilai menjadi satu nilai representatif (misalnya total, rata-rata, atau variasi). NumPy menyediakan fungsi-fungsi ini sebagai method langsung pada ndarray

In [9]:
import numpy as np

In [10]:
nilai = np.array([70, 85, 90, 60, 75])

print(nilai.sum())      # 380   → total keseluruhan
print(nilai.mean())     # 76.0  → rata-rata
print(np.median(nilai)) # 75.0  → nilai tengah setelah diurutkan
print(nilai.std())      # 10.42 → standar deviasi (sebaran data)
print(nilai.var())      # 108.6 → variance (std kuadrat)
print(nilai.min())      # 60    → nilai terkecil
print(nilai.max())      # 90    → nilai terbesar


380
76.0
75.0
10.677078252031311
114.0
60
90


Penjelasan kode di atas:

* `sum()`, `mean()`, `min()`, `max()`, `std()`, dan `var()` dapat digunakan sebagai method pada array, misalnya `nilai.mean()`.
* `median()` umumnya digunakan melalui fungsi NumPy, yaitu `np.median(nilai)`.
* `std()` mengukur penyebaran data dalam satuan yang sama dengan data asli.
* `var()` merupakan kuadrat dari `std()`, sehingga satuannya juga menjadi kuadrat dari satuan data.
* Fungsi-fungsi tersebut melakukan operasi terhadap array tanpa perlu menulis loop Python secara manual.


## 1.2 Position Aggregation — `argmin` & `argmax`

Berbeda dari `min()`/`max()` yang mengembalikan nilai, `argmin()`/`argmax()` mengembalikan posisi (indeks) dari nilai tersebut:

In [11]:
nilai = np.array([70, 85, 90, 60, 75])

print(f"Nilai Max {nilai.max()}")
print(f"Posisi Index nilai max: {nilai.argmax()}")

print(f"\nNilai min: {nilai.min()}")
print(f"Posisi Index nilai min: {nilai.argmin()}")

Nilai Max 90
Posisi Index nilai max: 2

Nilai min: 60
Posisi Index nilai min: 3


Penjelasan kode di atas:

* `argmax()` mengembalikan indeks posisi dari nilai terbesar, bukan nilai terbesarnya.
* `argmin()` mengembalikan indeks posisi dari nilai terkecil.
* Contoh penggunaan:

  ```python
  nama_siswa[nilai.argmax()]
  ```

  digunakan untuk mendapatkan nama siswa dengan nilai tertinggi.
* Pada output model klasifikasi, `argmax()` dapat digunakan untuk menentukan kelas dengan probabilitas tertinggi.
* Jika terdapat beberapa nilai maksimum/minimum yang sama, `argmax()`/`argmin()` mengembalikan indeks pertama yang ditemukan.


# 2. Axis


## 2.1 Konsep Axis pada Array Multidimensi

### Axis pada NumPy

`axis` adalah istilah NumPy untuk menunjukkan dimensi atau arah pada sebuah array. Parameter ini digunakan oleh banyak operasi agregasi seperti `sum()`, `mean()`, `min()`, dan `max()` untuk menentukan dimensi mana yang akan diringkas.

#### 1. Axis pada Array 1D

Array 1D hanya memiliki satu axis, yaitu `axis=0`.

```python
arr = np.array([10, 20, 30, 40])
````

```text
shape = (4,)
         ↑
      axis=0
```

Operasi:

```python
arr.sum(axis=0)
```

menghasilkan:

```text
10 + 20 + 30 + 40 = 100
```

Hasil:

```python
100
```

#### 2. Axis pada Array 2D

Array 2D memiliki dua axis:

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

Shape:

```text
shape = (2, 3)
         │  │
         │  └── axis=1
         └───── axis=0
```

Secara visual:

```text
        axis=1 →
        
        1   2   3
        4   5   6
        ↓
      axis=0
```

Untuk menghindari kebingungan, `axis=0` dapat dipahami sebagai arah vertikal dan `axis=1` sebagai arah horizontal.

#### 3. Agregasi Tanpa `axis`

Jika `axis` tidak diberikan:

```python
arr.sum()
```

NumPy menjumlahkan seluruh elemen array:

```text
1 + 2 + 3 + 4 + 5 + 6 = 21
```

Hasil:

```python
21
```

Shape hasil:

```text
(2, 3) → ()
```

Seluruh array diringkas menjadi satu nilai.

#### 4. Agregasi dengan `axis=0`

```python
arr.sum(axis=0)
```

Agregasi dilakukan sepanjang `axis=0`:

```text
       1   2   3
       4   5   6
       ↓   ↓   ↓
       +   +   +
       5   7   9
```

Perhitungan:

```text
1 + 4 = 5
2 + 5 = 7
3 + 6 = 9
```

Hasil:

```python
[5, 7, 9]
```

Shape:

```text
(2, 3) → (3,)
```

`axis=0` hilang karena dimensi tersebut telah diagregasi.

#### 5. Agregasi dengan `axis=1`

```python
arr.sum(axis=1)
```

Agregasi dilakukan sepanjang `axis=1`:

```text
1 + 2 + 3 = 6
4 + 5 + 6 = 15
```

Hasil:

```python
[6, 15]
```

Shape:

```text
(2, 3) → (2,)
```

`axis=1` hilang karena dimensi tersebut telah diagregasi.

### Ringkasan

| Operasi           | Axis yang diagregasi | Hasil       | Shape  |
| ----------------- | -------------------- | ----------- | ------ |
| `arr.sum()`       | Semua dimensi        | `21`        | `()`   |
| `arr.sum(axis=0)` | `axis=0`             | `[5, 7, 9]` | `(3,)` |
| `arr.sum(axis=1)` | `axis=1`             | `[6, 15]`   | `(2,)` |

### Inti

> `axis` menentukan dimensi yang digunakan sebagai arah agregasi. Dimensi yang diagregasi akan hilang dari `shape` hasil, sedangkan dimensi lainnya tetap dipertahankan.

```
```


## 2.2 axis=0 vs axis=1

* Kesalahan umum: mengira `axis=0` berarti operasi dilakukan per baris.
* Makna yang lebih tepat: `axis=0` berarti operasi dilakukan sepanjang arah baris, sehingga hasilnya tersisa per kolom.
* `axis=1` berarti operasi dilakukan sepanjang arah kolom, sehingga hasilnya tersisa per baris.


In [2]:
import numpy as np

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(matrix.sum(axis=0))   # [12, 15, 18]
print(matrix.sum(axis=1))   # [6, 15, 24]

[12 15 18]
[ 6 15 24]


![numpy_axis_0_vs_axis_1.png](../assets/figures/axis_0_vs_axis_1.png)

### 📖 Deep Dive — Cara Membaca axis yang Benar

* `axis` menunjukan dimensi array yang menjadi arah reduksi (reduction)
* `axis=0`: agregasi dilakukan sepanjang dimensi baris, sehingga dimensi `axis=0` dihilangkan dan menghasilkan satu nilai untuk setiap kolom.
* `axis=1`: agregasi dilakukan sepanjang dimensi kolom, sehingga dimensi `axis=1` dihilangkan dan menghasilkan satu nilai untuk setiap kolom.
* Prinsip utama: axis adalah dimensi yang di-collapse oleh operasi agregasi.
* Prinsip ini berlaku konsisten pada `sum()`, `mean()`, `std()`, `min()`, `max()`, dan fungsi agregasi lainnya.

## 2.3 keepdims dan Hubungannya dengan Broadcasting

* `keepdims` menentukan apakah dimensi yang digunakan dalam operasi agregasi dipertahankan dalam hasil
* Default: `keepdims=False` sehingga dimensi yang diagregasi dihilangkan.
* Dengan `keepdims=True`, dimensi tersebut tetap dipertahankan dengan ukuran 1.

### 1. Perilaku Default

In [4]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

(2, 3)


In [5]:
hasil = arr.mean(axis=0)
print(hasil)
print(f"Shape default: {hasil.shape}")

[2.5 3.5 4.5]
Shape default: (3,)


`axis=0` diagregasi, sehingga dimensi tersebut hilang

```text
______________________
Sebelum       : (2, 3)
                  ↓
mean(axis=0)  : (3,)
_______________________
```
Hasilnya memiliki satu nilai di setiap kolom

### 2. Dengan `keepdims=True`

In [6]:
hasil = arr.mean(axis=0, keepdims=True)

print(hasil)
print(f"Shape default: {hasil.shape}")


[[2.5 3.5 4.5]]
Shape default: (1, 3)


Dimensi `axis=0` tidak dihilangkan, tetapi ukurannya menjadi 1:


```text
______________________
Sebelum       : (2, 3)
                  ↓
mean(axis=0)  : (1, 3)
______________________
```

Perbandingan

| Operasi                       | Shape hasil | Dimensi agregasi          |
| ----------------------------- | ----------: | ------------------------- |
| `mean(axis=0)`                |      `(3,)` | Hilang                    |
| `mean(axis=0, keepdims=True)` |    `(1, 3)` | Dipertahankan sebagai `1` |




### 3.  keepdims untuk broadcasting

`keepdims=True` digunkana ketika hasil agrgasi akan digunakan kembali pada array asli
> Contoh: melakukan normalisasi berdasarkan rata-rata setiap kolom.

Tanpa `keepdims`:


In [8]:
mean = arr.mean(axis=0)
print(mean.shape)

(3,)


Dengan `keepdims`

In [9]:
mean = arr.mean(axis=0, keepdims=True)
print(mean.shape)

(1, 3)


shape `(1, 3)` secara eksplisit mempertahankan struktur dimensi kolom > mudah digunakan dalam operasi broadcasting terhadap array `(2, 3)`

In [11]:
normalize = arr - mean
print(normalize.shape)

(2, 3)


Broadcasting bekerja

```text
arr      : (2, 3)
mean     : (1, 3)
             ↓ broadcast
hasil    : (2, 3)
```

Secara konseptual

```text
arr:
[ 1  2  3 ]
[ 4  5  6 ]

mean:
[ 2.5  3.5  4.5 ]

arr - mean:
[-1.5 -1.5 -1.5]
[ 1.5  1.5  1.5]
```

### 4. Inti konsep

* `keepdims=False` > dimensi yang diagregasi dihilangkan.
* `keepdims=True` > dimensi yang diagregasi dipertahankan dengan dimensi 1.
* `keepdims=True` > membantu mempertahankan struktur array dimensi.
* Struktur tersebut sangat berguna ketika hasil agregasi akan digunakan kembali melalui broadcasting.
* Jadi, keepdims bukan mengubah nilai agregasi, tetapi mengubah shape hasilnya agar kompatibel dan lebih mudah digunakan dalam operasi lanjutan.

### Explain

In [13]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

hasil_default = matrix.sum(axis=1)
hasil_keepdims = matrix.sum(axis=1, keepdims=True)

print("Hasil Default")
print(hasil_default)
print(hasil_default.shape)
print("\nHasil dengan keepdims")
print(hasil_keepdims)
print(hasil_keepdims.shape)

Hasil Default
[ 6 15 24]
(3,)

Hasil dengan keepdims
[[ 6]
 [15]
 [24]]
(3, 1)


Penjelasan kode di atas:

- `axis=1` melakukan agregasi pada dimensi kolom untuk setiap baris.
- Tanpa `keepdims`, dimensi yang direduksi dihilangkan sehingga `shape` berubah dari `(3, 3)` menjadi `(3,)`.
- Dengan `keepdims=True`, dimensi yang direduksi tetap dipertahankan dengan ukuran `1`, sehingga `shape` berubah menjadi `(3, 1)`.
- Mempertahankan dimensi dengan ukuran `1` berguna untuk operasi broadcasting, karena dimensi tersebut dapat disesuaikan dengan dimensi array lain.

In [15]:
matrix_dikurangi_mean_baris = matrix - matrix.mean(axis=1, keepdims=True)
print(matrix_dikurangi_mean_baris)
print(matrix_dikurangi_mean_baris.shape)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
(3, 3)


Penjelasan kode di atas:

- `matrix.mean(axis=1, keepdims=True)` menghitung rata-rata setiap baris dan menghasilkan `shape (3, 1)`. Dimensi hasil agregasi tetap dipertahankan dengan ukuran `1`.
- Saat `matrix (3, 3)` dikurangi dengan hasil mean `(3, 1)`, broadcasting meregangkan dimensi berukuran `1` ke seluruh kolom. Dengan demikian, setiap baris dikurangi dengan rata-ratanya masing-masing.
- Jika menggunakan `matrix.mean(axis=1)` tanpa `keepdims`, hasilnya memiliki `shape (3,)`. Shape ini memang dapat dibroadcast terhadap `(3, 3)`, tetapi penyelarasan dilakukan terhadap dimensi terakhir sehingga nilai mean akan diterapkan berdasarkan kolom, bukan berdasarkan baris.
- Oleh karena itu, `keepdims=True` digunakan untuk mempertahankan struktur dimensi `(3, 1)` sehingga broadcasting berlangsung sesuai dengan struktur baris yang diinginkan.

# 3. Studi Kasus Data Science

## 3.1 Mean per Fitur

Dalam dataset tabular:

* Setiap kolom merepresentasikan satu fitur.
* Setiap baris merepresentasikan satu sampel atau observasi.
* Untuk menghitung rata-rata per fitur, agregasi dilakukan sepanjang baris pada setiap kolom.
* Karena baris berada pada `axis=0`, digunakan `axis=0`.
* Hasilnya adalah satu nilai rata-rata untuk setiap fitur.


In [17]:
data = np.array([[170, 65, 25],
                 [180, 80, 30],
                 [160, 55, 22]])

# kolom: tinggi (cm), berat (kg), usia (tahun)

mean_per_fitur = data.mean(axis=0)
# [170.   66.67 25.67]
print(mean_per_fitur)

[170.          66.66666667  25.66666667]


* `axis=0` mereduksi dimensi baris dan mempertahankan dimensi kolom.
* Dengan demikian, hasil `mean(axis=0)` berisi rata-rata masing-masing fitur.

## 3.2 Std per Fitur

* `std(axis=0)` menghitung standar deviasi untuk setiap fitur (kolom).
* Karena setiap kolom merepresentasikan satu fitur, agregasi dilakukan sepanjang baris (`axis=0`).
* Hasilnya adalah satu nilai standar deviasi untuk setiap fitur.

In [19]:
std_per_fitur = data.std(axis=0)
# [8.16, 10.27, 3.40]

print(std_per_fitur.shape)

(3,)


* Nilai `std` menunjukkan seberapa besar penyebaran data terhadap rata-ratanya.
* Semakin besar nilai `std`, semakin tinggi variasi data pada fitur tersebut.
* Informasi ini penting dalam tahap preprocessing, terutama untuk menentukan apakah fitur perlu dilakukan scaling atau standardisasi sebelum proses modeling.


## 3.3 Min/Max per Fitur

* `min(axis=0)` menghitung nilai minimum untuk setiap fitur (kolom).
* `max(axis=0)` menghitung nilai maksimum untuk setiap fitur (kolom).
* Karena agregasi dilakukan antar-sampel (baris), digunakan `axis=0`.




In [20]:
min_per_fitur = data.min(axis=0)
print(min_per_fitur)
# [160, 55, 22]

max_per_fitur = data.max(axis=0)
print(max_per_fitur)
# [180, 80, 30]

[160  55  22]
[180  80  30]


* Nilai minimum dan maksimum menunjukkan rentang nilai masing-masing fitur.
* Informasi ini dapat digunakan sebagai dasar untuk preprocessing, seperti normalisasi Min-Max.
* `mean`, `std`, `min`, dan `max` menggunakan `axis=0` ketika tujuannya adalah memperoleh satu statistik untuk setiap fitur.
* Pola ini umum digunakan dalam analisis dataset tabular, terutama pada tahap EDA dan preprocessing.

# Latihan Praktik

1. Statistik dasar — Diberikan `nilai_ujian = np.array([78, 92, 65, 88, 73, 95, 60])`, hitung mean, median, std, min, dan max dari array tersebut.

In [30]:
nilai_ujian = np.array([78, 92, 65, 88, 73, 95, 60])

print(f"Nilai mean: {nilai_ujian.mean():.2f}")
print(f"Nilai medain: {np.median(nilai_ujian):.2f}")
print(f"Nilai std: {nilai_ujian.std():.2f}")
print(f"Nilai max: {nilai_ujian.max()} & Nilai min: {nilai_ujian.min()}")

Nilai mean: 78.71
Nilai medain: 78.00
Nilai std: 12.53
Nilai max: 95 & Nilai min: 60


2. Posisi ekstrem — Menggunakan array yang sama, temukan indeks siswa dengan nilai tertinggi dan terendah menggunakan `argmax()` dan `argmin()`

In [33]:
print(f"Nilai Ujian: {nilai_ujian}")
print(f"\nNilai max: {nilai_ujian.max()}")
print(f"Posisi index: {nilai_ujian.argmax()}")

print(f"\nNilai min: {nilai_ujian.min()}")
print(f"Posisi index: {nilai_ujian.argmin()}")

Nilai Ujian: [78 92 65 88 73 95 60]

Nilai max: 95
Posisi index: 5

Nilai min: 60
Posisi index: 6


3. Prediksi axis — Diberikan array `data.shape = (5, 4)`, tuliskan (tanpa menjalankan kode) shape hasil dari `data.sum(axis=0)` dan `data.sum(axis=1)`, lalu verifikasi jawaban Anda dengan menjalankan kode sungguhan

In [35]:
arr_3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20]
])

print(arr_3.shape)

print(arr_3.sum(axis=0))
print(arr_3.sum(axis=1))

(5, 4)
[45 50 55 60]
[10 26 42 58 74]


4. keepdims untuk broadcasting — Diberikan matrix data berukuran (4, 3), kurangi setiap baris dengan mean barisnya sendiri menggunakan keepdims=True, lalu buktikan bahwa tanpa keepdims=True operasi tersebut akan memicu ValueError atau hasil yang salah.

In [36]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [15, 25, 35]
])

print(data)
print(data.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 35]]
(4, 3)


Mean setiap baris

In [37]:
mean_baris = data.mean(axis=1, keepdims=True)
print(mean_baris)
print(mean_baris.shape)

[[20.]
 [50.]
 [80.]
 [25.]]
(4, 1)


Kurangi setiap baris dengan mean barisnya

In [38]:
data_centered = data - mean_baris
print(data_centered)
print(data_centered.shape)

[[-10.   0.  10.]
 [-10.   0.  10.]
 [-10.   0.  10.]
 [-10.   0.  10.]]
(4, 3)


Tanpa `keepdims=True`

In [39]:
mean_baris = data.mean(axis=1)

print(mean_baris.shape)
# (4,)

(4,)


In [40]:
data - mean_baris

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

```text
data       → (4, 3)
mean_baris →    (4,)
```

NumPy menyelaraskan (4,) dengan dimensi terakhir (3). Karena 4 ≠ 3